import Head from 'next/head';
import { Poppins } from 'next/font/google';
import { useEffect, useState } from 'react';
import useFileReader from '@/hooks/useFileReader';
import ReactDiffViewer from 'react-diff-viewer';
import { FileInput } from 'flowbite-react';
const inter = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
});

const Toggle = ({
  checked,
  onChange,
  label,
}: {
  checked: boolean;
  onChange: () => void;
  label: string;
}) => (
  <label className='relative inline-flex items-center cursor-pointer'>
    <input
      type='checkbox'
      className='sr-only peer'
      checked={checked}
      onChange={onChange}
    />
    <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600" />
    <span className='ml-3 text-sm font-medium text-white'>{label}</span>
  </label>
);

export default function Home() {
  const [first, setFirst, firstMetadata] = useFileReader();
  const [second, setSecond, secondMetadata] = useFileReader();
  const [settings, setSettings] = useState<Record<string, boolean>>({
    splitView: true,
    darkEditor: true,
    showDiffOnly: true,
  });
  const [diffState, setDiffState] = useState<any>();
  useEffect(() => {
    if (first && second) {
      setDiffState({
        first,
        second,
      });
    }
  }, [first, second]);

  return (
    <>
      <Head>
        <title>The Comparator</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${inter.className}`}>
        <div className='flex flex-col justify-center items-center w-full min-h-screen'>
          {!diffState?.first && (
            <>
              <h1 className='text-6xl font-bold my-3'>Diff</h1>
              <p className='text-xl my-3'>
                Upload any two <span className='text-yellow-300'>text</span>{' '}
                files below to compare them.
              </p>
              <span className='text-gray-400 text-sm'>
                (.txt, .json, .csv, any programming language supported.)
              </span>
              <div className='flex justify-around items-center w-full max-w-4xl mt-12'>
                <FileInput onChange={setFirst} />
                <FileInput onChange={setSecond} />
              </div>
            </>
          )}
          {diffState?.first && (
            <>
              <div className='flex justify-around items-center w-full px-32 my-12'>
                <Toggle
                  label='Split the view'
                  onChange={() =>
                    setSettings((settings) => ({
                      ...settings,
                      splitView: !settings.splitView,
                    }))
                  }
                  checked={settings.splitView}
                />
                <Toggle
                  label='Show only different lines'
                  onChange={() =>
                    setSettings((settings) => ({
                      ...settings,
                      showDiffOnly: !settings.showDiffOnly,
                    }))
                  }
                  checked={settings.showDiffOnly}
                />
                <Toggle
                  label='Use dark preview background'
                  onChange={() =>
                    setSettings((settings) => ({
                      ...settings,
                      darkEditor: !settings.darkEditor,
                    }))
                  }
                  checked={settings.darkEditor}
                />
              </div>
              <ReactDiffViewer
                leftTitle={firstMetadata?.name}
                rightTitle={secondMetadata?.name}
                oldValue={diffState.first}
                newValue={diffState.second}
                splitView={settings.splitView}
                useDarkTheme={settings.darkEditor}
                showDiffOnly={settings.showDiffOnly}
              />
            </>
          )}
        </div>
      </main>
    </>
  );
}
